
--Texts (translate)
if buttons.assign() then _button = "X" else _button = "O" end

strings = {

--Config Menu
"Scansiona i Salvataggi",			--1
"Scansiona VHBL",			--2
"Scannsiona Games",			--3
"Scansiona le Categorie",		--4
"Slides",				--5
"Scansiona i contenuti Nascosti",			--6
"Visualizza i contenuti Nascosti",			--7
"Cancella contenuti Nascosti",		--8
"Visualizza PICs",			--9
"BarColor",				--10
"Boot",					--11
"Riavvia",				--12
"Cancella",				--13
"Nascondi",					--14
"Quadrato",				--15 boot 0
"Triangolo",				--16 boot 1
"Cerchio",				--17 boot 2
"Croce",				--18 boot 3
"No",					--19 boot4
"Visualizza",					--20
"Premere ".._button,		--21

--Options
yes="Si",
no="No",
up="Su",
down="Giu",

--Delete ONEMenu.ini
delini="Cancella ONEMENU.INI",

--Menu
nogames="NO GAMES",

--Scans
saves="Scansiona i SALVATAGGI",
catiso="Scansiona le ISO (Incluse le Categorie)",
iso="Scansiona le ISO",
vhbl="Scansiona PSP/VHBL",
gamecat="Scansiona PSP/GAME (Incluse le Categorie)",
game="Scansiona PSP/GAME",

--Install Zip
progress="Install on Progress",
file="File: ",
rem="Remaining: ",
spd="Velocita: ",
nospace="Spazio Insufficiente",
start=_button.." per avviare l' installazione",
nopbp="No PBPs!",
already="Questo contenuto e' stato installato. X: Per Sovrascrivere - O: Per Rinominare ?",
startin=_button.." per avviare l'installazione in ",

--Optios Menu Explorer
back=" Return ",
copyfile="Copiare i File : ",
delfile="Cancellare i file : ",
label="Attendere prego...\nCaricamento immagine...",
background="Background: Premere Triangolo",
dir="<DIR>",
copy = "Copia",
delete = "Cancella ",
makedir = "MakeDir",
rename = "Rinomina",
extract = "Estrarre",
cancel = "Cancella",
ftp = "FTP",
serverftp = "Server ftp://",
closeftp = "Premere START per chiudere la connessione FTP",
loseftp = "Connessione FTP Chiusa",
base_headers="Headers.bin",
extractto = "Estrarre su",
paste = "Incolla",
move = "Sposta",
pass="Usare Pass ?",
creatfolder="Crea una Cartella",
newfolder="Nuova Cartella",
ospass="PASS",

--Texto para dumpear base_headers en PS1
headers_ok="Headers OK",
headers_fails="Headers FAILS",

}
